// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library UniqueIdx {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "uniqueIdx", name: "UniqueIdx", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462756e697175654964780000000000556e6971756549647800000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000100000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, bytes32, bytes32)
  Schema constant _keySchema = Schema.wrap(0x006003005f5f5f00000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32[])
  Schema constant _valueSchema = Schema.wrap(0x00000001c1000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "sourceTableId";
    keyNames[1] = "indexesHash";
    keyNames[2] = "valuesHash";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "keyTuple";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config (using the specified store).
   */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get keyTuple.
   */
  function getKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (bytes32[] memory keyTuple) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get keyTuple.
   */
  function _getKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (bytes32[] memory keyTuple) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get keyTuple (using the specified store).
   */
  function getKeyTuple(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (bytes32[] memory keyTuple) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    bytes memory _blob = _store.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get keyTuple.
   */
  function get(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (bytes32[] memory keyTuple) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get keyTuple.
   */
  function _get(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (bytes32[] memory keyTuple) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get keyTuple (using the specified store).
   */
  function get(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (bytes32[] memory keyTuple) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    bytes memory _blob = _store.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Set keyTuple.
   */
  function setKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    bytes32[] memory keyTuple
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((keyTuple)));
  }

  /**
   * @notice Set keyTuple.
   */
  function _setKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    bytes32[] memory keyTuple
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((keyTuple)));
  }

  /**
   * @notice Set keyTuple (using the specified store).
   */
  function setKeyTuple(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    bytes32[] memory keyTuple
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    _store.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((keyTuple)));
  }

  /**
   * @notice Set keyTuple.
   */
  function set(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash, bytes32[] memory keyTuple) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((keyTuple)));
  }

  /**
   * @notice Set keyTuple.
   */
  function _set(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash, bytes32[] memory keyTuple) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((keyTuple)));
  }

  /**
   * @notice Set keyTuple (using the specified store).
   */
  function set(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    bytes32[] memory keyTuple
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    _store.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((keyTuple)));
  }

  /**
   * @notice Get the length of keyTuple.
   */
  function lengthKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of keyTuple.
   */
  function _lengthKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of keyTuple (using the specified store).
   */
  function lengthKeyTuple(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    uint256 _byteLength = _store.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of keyTuple.
   */
  function length(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of keyTuple.
   */
  function _length(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of keyTuple (using the specified store).
   */
  function length(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    uint256 _byteLength = _store.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of keyTuple.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of keyTuple.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of keyTuple (using the specified store).
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemKeyTuple(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _blob = _store.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of keyTuple.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItem(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of keyTuple.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItem(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of keyTuple (using the specified store).
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItem(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _blob = _store.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Push an element to keyTuple.
   */
  function pushKeyTuple(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to keyTuple.
   */
  function _pushKeyTuple(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to keyTuple (using the specified store).
   */
  function pushKeyTuple(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    _store.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to keyTuple.
   */
  function push(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to keyTuple.
   */
  function _push(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to keyTuple (using the specified store).
   */
  function push(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    _store.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from keyTuple.
   */
  function popKeyTuple(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from keyTuple.
   */
  function _popKeyTuple(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from keyTuple (using the specified store).
   */
  function popKeyTuple(IStore _store, ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    _store.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from keyTuple.
   */
  function pop(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from keyTuple.
   */
  function _pop(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from keyTuple (using the specified store).
   */
  function pop(IStore _store, ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    _store.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Update an element of keyTuple at `_index`.
   */
  function updateKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of keyTuple at `_index`.
   */
  function _updateKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of keyTuple (using the specified store) at `_index`.
   */
  function updateKeyTuple(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      _store.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of keyTuple at `_index`.
   */
  function update(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of keyTuple at `_index`.
   */
  function _update(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of keyTuple (using the specified store) at `_index`.
   */
  function update(
    IStore _store,
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      _store.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys (using the specified store).
   */
  function deleteRecord(IStore _store, ResourceId sourceTableId, bytes32 indexesHash, bytes32 valuesHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    _store.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(bytes32[] memory keyTuple) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(keyTuple.length * 32);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(bytes32[] memory keyTuple) internal pure returns (bytes memory) {
    return abi.encodePacked(EncodeArray.encode((keyTuple)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(bytes32[] memory keyTuple) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(keyTuple);
    bytes memory _dynamicData = encodeDynamic(keyTuple);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(
    ResourceId sourceTableId,
    bytes32 indexesHash,
    bytes32 valuesHash
  ) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = indexesHash;
    _keyTuple[2] = valuesHash;

    return _keyTuple;
  }
}
