// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { BasicIdx, BasicIdxData } from "./tables/BasicIdx.sol";
import { BasicIdxUsedKeys } from "./tables/BasicIdxUsedKeys.sol";
import { BasicIdxMetadata, BasicIdxMetadataData } from "./tables/BasicIdxMetadata.sol";
