// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { UniqueIdx_Equipment_EquipmentTypeName } from "./idxs/UniqueIdx_Equipment_EquipmentTypeName.sol";
import { Idx_Equipment_Entity } from "./idxs/Idx_Equipment_Entity.sol";
import { Idx_Equipment_Level } from "./idxs/Idx_Equipment_Level.sol";
import { Idx_Equipment_EquipmentTypeLevel } from "./idxs/Idx_Equipment_EquipmentTypeLevel.sol";
import { Idx_Equipment_Name } from "./idxs/Idx_Equipment_Name.sol";
import { Idx_Equipment_TypeNameSlots } from "./idxs/Idx_Equipment_TypeNameSlots.sol";
import { Idx_Position_MatchEntityXY } from "./idxs/Idx_Position_MatchEntityXY.sol";

function batchRegisterIdxs() {
  UniqueIdx_Equipment_EquipmentTypeName.register();
  Idx_Equipment_Entity.register();
  Idx_Equipment_Level.register();
  Idx_Equipment_EquipmentTypeLevel.register();
  Idx_Equipment_Name.register();
  Idx_Equipment_TypeNameSlots.register();
  Idx_Position_MatchEntityXY.register();
}
