// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";

// Import idx internals
import { Uint8Map, Uint8MapLib } from "@dk1a/mud-table-idxs/src/Uint8Map.sol";
import { hashIndexes, hashValues } from "@dk1a/mud-table-idxs/src/utils.sol";

import { registerBasicIdx } from "@dk1a/mud-table-idxs/src/namespaces/basicIdx/registerBasicIdx.sol";
import { BasicIdx } from "@dk1a/mud-table-idxs/src/namespaces/basicIdx/codegen/tables/BasicIdx.sol";
import { BasicIdxUsedKeys } from "@dk1a/mud-table-idxs/src/namespaces/basicIdx/codegen/tables/BasicIdxUsedKeys.sol";
import { BasicIdx_KeyTuple } from "@dk1a/mud-table-idxs/src/namespaces/basicIdx/BasicIdx_KeyTuple.sol";

// Import user types
import { EquipmentType } from "../../../../codegen/common.sol";

library Idx_Equipment_TypeNameSlots {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "Equipment", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462000000000000000000000000000045717569706d656e7400000000000000);

  uint256 constant _keyNumber = 0;
  uint256 constant _fieldNumber = 3;

  Uint8Map constant _keyIndexes = Uint8Map.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  Uint8Map constant _fieldIndexes = Uint8Map.wrap(0x0300020300000000000000000000000000000000000000000000000000000000);

  bytes32 constant _indexesHash = 0xd327e0e1f28fac4a937d22c7c55eae382629958842a6d7167aca4f3720830177;

  function valuesHash(
    EquipmentType equipmentType,
    string memory name,
    bytes32[] memory slots
  ) internal pure returns (bytes32) {
    bytes32[] memory _partialKeyTuple = new bytes32[](_keyNumber);

    bytes[] memory _partialValues = new bytes[](_fieldNumber);

    _partialValues[0] = abi.encodePacked(uint8(equipmentType));

    _partialValues[1] = bytes((name));

    _partialValues[2] = EncodeArray.encode((slots));

    return hashValues(_partialKeyTuple, _partialValues);
  }

  // Should be called once in e.g. PostDeploy
  function register() internal {
    registerBasicIdx(_tableId, _keyIndexes, _fieldIndexes);
  }

  function length(
    EquipmentType equipmentType,
    string memory name,
    bytes32[] memory slots
  ) internal view returns (uint256) {
    bytes32 _valuesHash = valuesHash(equipmentType, name, slots);

    return BasicIdx_KeyTuple.length(_tableId, _indexesHash, _valuesHash);
  }

  function hasKeyTuple(bytes32[] memory _keyTuple) internal view returns (bool _has, uint40 _index) {
    bytes32 _keyTupleHash = keccak256(abi.encode(_keyTuple));

    return BasicIdxUsedKeys.get(_tableId, _indexesHash, _keyTupleHash);
  }

  function has(bytes32 entity) internal view returns (bool _has, uint40 _index) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = entity;

    return hasKeyTuple(_keyTuple);
  }

  function getKeyTuple(
    EquipmentType equipmentType,
    string memory name,
    bytes32[] memory slots,
    uint256 _index
  ) internal view returns (bytes32[] memory _keyTuple) {
    bytes32 _valuesHash = valuesHash(equipmentType, name, slots);

    return BasicIdx_KeyTuple.getItem(_tableId, _indexesHash, _valuesHash, _index, 1);
  }

  function get(
    EquipmentType equipmentType,
    string memory name,
    bytes32[] memory slots,
    uint256 _index
  ) internal view returns (bytes32 entity) {
    bytes32[] memory _keyTuple = getKeyTuple(equipmentType, name, slots, _index);

    entity = _keyTuple[0];
  }

  /**
   * @notice Decode keys from a bytes32 array using the source table's field layout.
   */
  function decodeKeyTuple(bytes32[] memory _keyTuple) internal pure returns (bytes32 entity) {
    entity = _keyTuple[0];
  }
}
