// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { UniqueIdx } from "./tables/UniqueIdx.sol";
import { UniqueIdxMetadata, UniqueIdxMetadataData } from "./tables/UniqueIdxMetadata.sol";
